### ISSUE TITLE
Fails in conjunction with the 2.6 date field calender

### ISSUE THREAD

**Issue by animaux** [hananils/association_ui_selector#41]
Not sure which one is the perpetrator or if it’s the combination of both:

![bildschirmfoto 2015-01-06 um 10 00 19](https://cloud.githubusercontent.com/assets/446874/5626399/0e76face-958b-11e4-9b02-f54d8de32d9a.png)

The selector interface should be active.

**Comment by nilshoerrmann** [comment]
Interesting. 

Are you using any other JS-based extensions? 
And does the calendar work, if the AUI is deactivated?

**Comment by animaux** [comment]
I found the poodle’s core! It’s not the association_ui_selector at fault. It’s german localisation messing things up. Should I post an issue there, or in the symphony repository?

**Comment by nilshoerrmann** [comment]
Wie kann denn die deutsche Übersetzung da hereinfunken?!

**Comment by animaux** [comment]
Kein schimmer, aber sobald die aus ist funktioniert der Kalender tippitoppi :dancers:

**Comment by animaux** [comment]
Also sobald das System auf »english« eingestellt ist.

**Comment by nilshoerrmann** [comment]
Oh. Moment.

**Comment by nilshoerrmann** [comment]
Vielleicht liegt hier das Problem: https://github.com/symphonycms/symphony-2/blob/integration/symphony/assets/js/src/symphony.calendar.js#L22

Könntest Du das in der Hauptrepo als Problem melden? Danke!

**Comment by animaux** [comment]
K!
