### ISSUE TITLE
Tags - Existing Values filtering

### ISSUE THREAD

**Issue by jonmifsud** [hananils/association_ui_selector#42]
It would be nice to allow the Association UI to pull in tags which have already been used within the field. Association UI works fine when tags fetch suggestions from another field/section, I'm not sure how much work it would be be to allow the 'Autocomplete' functionality on Existing Values.

**Comment by jonmifsud** [comment]
@nilshoerrmann after further thought I think this is best as a separate extension. Making the 'ui' available for tag lists would require some core changes, where as through an extension it can match the tagfield class. Unless you'd like to see this merged within the Association UI, I'll be releasing a separate extension within the coming days with the mentioned functionality (based on the Association UI Selector).

**Comment by nilshoerrmann** [comment]
I'm not sure if I fully understand you idea (and thus your reasoning to move it to a separate extension) yet.

**Comment by jonmifsud** [comment]
Sorry for not being clear.

> Please keep in mind that interface are only available in combination with dynamic values, if you are using default select boxes or tag lists.

The current interface does not support Tag Lists using pre-existing values as suggestions. My request was to extend the current UI to support pre-existing values within tags. I got this working with an additional content page + some JS/CSS. I was thinking it should be separate as it's not exactly a UI for Associations.

**Comment by nilshoerrmann** [comment]
Ah! Thanks for clarifying. 

> I got this working with an additional content page + some JS/CSS.

Can't you just reuse what the tag list field provides in the markup already? Just providing a different interface to show the existing tags?

> I was thinking it should be separate as it's not exactly a UI for Associations.

Yes, going with a separate extension sounds like a good option.

**Comment by jonmifsud** [comment]
> Can't you just reuse what the tag list field provides in the markup already? Just providing a different interface to show the existing tags?

Not sure.. I've imported something like 40 articles and the list looked quite large. Not sure how it would handle having thousands of entries with different tags... So I might end up having to limit/remove the preselected list. Additionally though the interface I can support filtering if required.

Thanks for the feedback so I'm closing this issue (one less to worry about)
